package com.divine.visitormanagement_v1.model;

import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;

/**
 * VisitorCode entity maps to the 'visitor_codes' table.
 * Stores generated codes, visitor info, and links to residents and addresses.
 * Codes have an expiration for daily cleanup.
 */
@Entity
@Table(name = "visitor_codes")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class VisitorCode {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String code;

    @Column(name = "visitor_name", nullable = false)
    private String visitorName;

    /**
     * Many-to-one relationship to Resident.
     * Each code is generated by a resident.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "resident_id")
    private Resident resident;

    /**
     * Many-to-one relationship to HouseAddress.
     * Each code is associated with a house address.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "house_address_id")
    private HouseAddress houseAddress;

    @Column(name = "generated_at", nullable = false)
    private LocalDateTime generatedAt;

    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    @PrePersist
    protected void onCreate() {
        generatedAt = LocalDateTime.now();
    }
}
